Fix compilation error for exported model definitions that have recursive relationships
e.g.
```objc
@interface TestObject1 : RLMObject

@property RLMArray<TestObject2 *><TestObject2> *objects;

@end

@interface TestObject2 : RLMObject

@property RLMArray<TestObject1 *><TestObject1> *objects;

@end
```

If models have recursive to-many relationships each other like above, the `Save Objective-C definitions` generate model files that have the following compilation error:
`Type argument 'TestObject2 *' does not satisfy the bound ('RLMObject *') of type parameter 'RLMObjectType'`

Because generics type parameter cannot recognize the subclass of the RLMObject from `@class` forwarding declarations.
So use `@interface ...` for forwarding declarations instead `@class`. Then, `class extension` for property declarations.
Like the following:

```objc
@interface TestObject1 : RLMObject
@end

@interface TestObject2 : RLMObject
@end

RLM_ARRAY_TYPE(TestObject1)
RLM_ARRAY_TYPE(TestObject2)

@interface TestObject1()

@property RLMArray<TestObject2 *><TestObject2> *objects;

@end

@interface TestObject2()

@property RLMArray<TestObject1 *><TestObject1> *objects;

@end
```